/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventana;

import moldes.Carro;
/**
 *
 * @author Edwin ballesteros
 */
public class conducirCarro extends javax.swing.JFrame {

    Carro car;
    Carro carros[];
    int contador=0;
    
    
    public conducirCarro() {
        initComponents();
        this.setLocationRelativeTo(null);
        carros = new Carro[3];
    }
public void actualizar() {
			
	jltitulo2.setText("Estado Carro: "+car.getPlaca());
		
	if(car.getEstadoMotor()) {
		    jlmotor.setText("Motor: ENCENDIDO");
	    }else {
			jlmotor.setText("Motor: APAGADO");
	   }
	jlnivel.setText("Nivel de Batería: "+String.valueOf(car.getNivelBateria())+" %");
    jlvelocidad.setText("Velocidad: "+String.valueOf(car.getVelocidad())+" Kl/h");
	
		}
	
	public void limpiar() {
		jtplaca.setText("");
		jtcolor.setText("");
		jtmodelo.setText("0");
		jtmarca.setText("");
		jtplaca.requestFocus();
	}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtplaca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtcolor = new javax.swing.JTextField();
        jtmodelo = new javax.swing.JTextField();
        jtmarca = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jbcrear = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jbprender = new javax.swing.JButton();
        jbapagar = new javax.swing.JButton();
        jbacelerar = new javax.swing.JButton();
        jbfrenar = new javax.swing.JButton();
        jclista = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jltitulo2 = new javax.swing.JLabel();
        jlmotor = new javax.swing.JLabel();
        jlnivel = new javax.swing.JLabel();
        jlvelocidad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Placa:");

        jtplaca.setText(" ");
        jtplaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtplacaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Color:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Modelo:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Marca:");

        jtcolor.setText(" ");

        jtmodelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtmodeloActionPerformed(evt);
            }
        });

        jtmarca.setText(" ");

        jLabel5.setBackground(new java.awt.Color(51, 51, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Datos Conducir");

        jbcrear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbcrear.setText("Crear");
        jbcrear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbcrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtplaca, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jtcolor, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                        .addComponent(jtmodelo))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jbcrear))
                                    .addComponent(jtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel5)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtplaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtcolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbcrear)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        jLabel10.setText("Conducir Carro");

        jbprender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbprender.setText("Prender");
        jbprender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbprenderActionPerformed(evt);
            }
        });

        jbapagar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbapagar.setText("Apagar");
        jbapagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbapagarActionPerformed(evt);
            }
        });

        jbacelerar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbacelerar.setText("Acelerar");
        jbacelerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbacelerarActionPerformed(evt);
            }
        });

        jbfrenar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbfrenar.setText("Frenar");
        jbfrenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbfrenarActionPerformed(evt);
            }
        });

        jclista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione carro", "Carro 1", "Carro 2", "Carro 3" }));
        jclista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jclistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbprender)
                    .addComponent(jbacelerar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbapagar)
                    .addComponent(jbfrenar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jclista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jclista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbapagar)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jbprender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbacelerar)
                            .addComponent(jbfrenar))))
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 326, 309, 130));

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));

        jltitulo2.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        jltitulo2.setText("Estado Carro");

        jlmotor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlmotor.setText("Motor:  ____________________");

        jlnivel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlnivel.setText("Nivel Bateria:  _____________");

        jlvelocidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlvelocidad.setText("Velocidad:  ____________Kl/h");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jltitulo2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlnivel)
                            .addComponent(jlmotor)
                            .addComponent(jlvelocidad))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jltitulo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlmotor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlnivel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlvelocidad)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 194, 309, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtplacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtplacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtplacaActionPerformed

    private void jbapagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbapagarActionPerformed
        // TODO add your handling code here:
                    car.apagar();
			actualizar();
			jbprender.setEnabled(true);
			jbapagar.setEnabled(false);
    }//GEN-LAST:event_jbapagarActionPerformed

    private void jtmodeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtmodeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtmodeloActionPerformed

    private void jbcrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcrearActionPerformed
        // TODO add your handling code here:
        
        String pl, cl, marc;
			int mod;
			pl=jtplaca.getText();
			cl=jtcolor.getText();
			marc=jtmarca.getText();
			mod=Integer.parseInt(jtmodelo.getText());
			
			car = new Carro(pl,cl,mod,marc);
		 
			carros[contador]=car;
			contador++;
			jbcrear.setText("Crear carro "+(contador+1));
			if(contador>=3){
				
				//jpdatos.setVisible(false);
				jbcrear.setEnabled(false);
				jbcrear.setText("Crear carro ");
			}
			limpiar();
			//actualizar();
						

    }//GEN-LAST:event_jbcrearActionPerformed

    private void jbprenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbprenderActionPerformed
        // TODO add your handling code here:
        car.encender();
			actualizar();
			jbprender.setEnabled(false);
			jbapagar.setEnabled(true);
    }//GEN-LAST:event_jbprenderActionPerformed

    private void jbacelerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbacelerarActionPerformed
        // TODO add your handling code here:
        car.acelerar();
        actualizar();
    }//GEN-LAST:event_jbacelerarActionPerformed

    private void jbfrenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbfrenarActionPerformed
        // TODO add your handling code here:
        	car.frenar();
	        actualizar();
    }//GEN-LAST:event_jbfrenarActionPerformed

    private void jclistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jclistaActionPerformed
        // TODO add your handling code here:
        if(jclista.getSelectedItem()=="Seleccione carro") {
				
			System.out.println("Debe seleccionar un carro");	
				
			}else {
				car=carros[jclista.getSelectedIndex()-1];
				actualizar();
			} 
        
    }//GEN-LAST:event_jclistaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(conducirCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(conducirCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(conducirCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(conducirCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new conducirCarro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbacelerar;
    private javax.swing.JButton jbapagar;
    private javax.swing.JButton jbcrear;
    private javax.swing.JButton jbfrenar;
    private javax.swing.JButton jbprender;
    private javax.swing.JComboBox<String> jclista;
    private javax.swing.JLabel jlmotor;
    private javax.swing.JLabel jlnivel;
    private javax.swing.JLabel jltitulo2;
    private javax.swing.JLabel jlvelocidad;
    private javax.swing.JTextField jtcolor;
    private javax.swing.JTextField jtmarca;
    private javax.swing.JTextField jtmodelo;
    private javax.swing.JTextField jtplaca;
    // End of variables declaration//GEN-END:variables
}
